/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author riyavirani
 */
public class PatientMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientSearchJPanelNew
     */
    public PatientMainJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        PatientNavPanel = new javax.swing.JPanel();
        btnSearchHosp = new javax.swing.JButton();
        btnEncounterHistory = new javax.swing.JButton();
        btnAddNewVitals = new javax.swing.JButton();
        PatientRightPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(181, 212, 243));
        setPreferredSize(new java.awt.Dimension(1250, 1200));
        setSize(new java.awt.Dimension(1250, 1200));

        splitPane.setBackground(new java.awt.Color(181, 212, 243));
        splitPane.setDividerLocation(215);

        PatientNavPanel.setBackground(new java.awt.Color(181, 212, 243));
        PatientNavPanel.setPreferredSize(new java.awt.Dimension(215, 1222));

        btnSearchHosp.setText("Search Hospitals/Doctors");
        btnSearchHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchHospActionPerformed(evt);
            }
        });

        btnEncounterHistory.setText("View Previous Encounters");

        btnAddNewVitals.setText("Add New Vitals");

        javax.swing.GroupLayout PatientNavPanelLayout = new javax.swing.GroupLayout(PatientNavPanel);
        PatientNavPanel.setLayout(PatientNavPanelLayout);
        PatientNavPanelLayout.setHorizontalGroup(
            PatientNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PatientNavPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PatientNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSearchHosp)
                    .addComponent(btnEncounterHistory)
                    .addComponent(btnAddNewVitals))
                .addGap(17, 17, 17))
        );

        PatientNavPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddNewVitals, btnEncounterHistory, btnSearchHosp});

        PatientNavPanelLayout.setVerticalGroup(
            PatientNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientNavPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnSearchHosp)
                .addGap(40, 40, 40)
                .addComponent(btnEncounterHistory)
                .addGap(40, 40, 40)
                .addComponent(btnAddNewVitals)
                .addContainerGap(973, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(PatientNavPanel);

        PatientRightPanel.setBackground(new java.awt.Color(181, 212, 243));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        jLabel1.setText("Welcome");

        javax.swing.GroupLayout PatientRightPanelLayout = new javax.swing.GroupLayout(PatientRightPanel);
        PatientRightPanel.setLayout(PatientRightPanelLayout);
        PatientRightPanelLayout.setHorizontalGroup(
            PatientRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientRightPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(769, Short.MAX_VALUE))
        );
        PatientRightPanelLayout.setVerticalGroup(
            PatientRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientRightPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addContainerGap(1063, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(PatientRightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchHospActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchHospActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PatientNavPanel;
    private javax.swing.JPanel PatientRightPanel;
    private javax.swing.JButton btnAddNewVitals;
    private javax.swing.JButton btnEncounterHistory;
    private javax.swing.JButton btnSearchHosp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
